### ISSUE TITLE
maaf bang ini saya benar-benar pemula mau tanya tentang bug, terjadi saat cetak hasil ujian

### ISSUE THREAD

**Issue by ronikholis** [arfandotid/ujian-online-ci#4]
A PHP Error was encountered
Severity: 8192
Message: Array and string offset access syntax with curly braces is deprecated
Filename: tcpdf/tcpdf.php
Line Number: 16900
Backtrace:
File: D:\xampp\htdocs\coding\ujian-online-ci-master\application\libraries\Pdf.php
Line: 3
Function: _error_handler 
File: D:\xampp\htdocs\coding\ujian-online-ci-master\application\libraries\Pdf.php
Line: 3
Function: require_once 
File: D:\xampp\htdocs\coding\ujian-online-ci-master\application\controllers\Hasilujian.php
Line: 73
Function: library 
File: D:\xampp\htdocs\coding\ujian-online-ci-master\index.php
Line: 315
Function: require_once 
A PHP Error was encountered
Severity: 8192
Message: Array and string offset access syntax with curly braces is deprecated
Filename: tcpdf/tcpdf.php
Line Number: 16900
Backtrace:
File: D:\xampp\htdocs\coding\ujian-online-ci-master\application\libraries\Pdf.php
Line: 3
Function: _error_handler 
File: D:\xampp\htdocs\coding\ujian-online-ci-master\application\libraries\Pdf.php
Line: 3
Function: require_once 
File: D:\xampp\htdocs\coding\ujian-online-ci-master\application\controllers\Hasilujian.php
Line: 73
Function: library 
File: D:\xampp\htdocs\coding\ujian-online-ci-master\index.php
Line: 315
Function: require_once 
A PHP Error was encountered
Severity: 8192
Message: Array and string offset access syntax with curly braces is deprecated
Filename: tcpdf/tcpdf.php
Line Number: 16903
Backtrace:
File: D:\xampp\htdocs\coding\ujian-online-ci-master\application\libraries\Pdf.php
Line: 3
Function: _error_handler 
File: D:\xampp\htdocs\coding\ujian-online-ci-master\application\libraries\Pdf.php
Line: 3
Function: require_once 
File: D:\xampp\htdocs\coding\ujian-online-ci-master\application\controllers\Hasilujian.php
Line: 73
Function: library 
File: D:\xampp\htdocs\coding\ujian-online-ci-master\index.php
Line: 315
Function: require_once 
A PHP Error was encountered
Severity: 8192
Message: Array and string offset access syntax with curly braces is deprecated
Filename: include/tcpdf_images.php
Line Number: 314
Backtrace:
File: D:\xampp\htdocs\coding\ujian-online-ci-master\application\libraries\tcpdf\tcpdf.php
Line: 119
Function: _error_handler 
File: D:\xampp\htdocs\coding\ujian-online-ci-master\application\libraries\tcpdf\tcpdf.php
Line: 119
Function: require_once 
File: D:\xampp\htdocs\coding\ujian-online-ci-master\application\libraries\Pdf.php
Line: 3
Function: require_once 
File: D:\xampp\htdocs\coding\ujian-online-ci-master\application\controllers\Hasilujian.php
Line: 73
Function: library 
File: D:\xampp\htdocs\coding\ujian-online-ci-master\index.php
Line: 315
Function: require_once 
A PHP Error was encountered
Severity: Warning
Message: chr() expects parameter 1 to be int, string given
Filename: include/tcpdf_fonts.php
Line Number: 1671
Backtrace:
File: D:\xampp\htdocs\coding\ujian-online-ci-master\application\libraries\tcpdf\include\tcpdf_fonts.php
Line: 1671
Function: chr 
File: D:\xampp\htdocs\coding\ujian-online-ci-master\application\libraries\tcpdf\include\tcpdf_fonts.php
Line: 1803
Function: unichr 
File: D:\xampp\htdocs\coding\ujian-online-ci-master\application\libraries\tcpdf\include\tcpdf_fonts.php
Line: 2099
Function: UTF8ArrSubString 
File: D:\xampp\htdocs\coding\ujian-online-ci-master\application\libraries\tcpdf\tcpdf.php
Line: 1963
Function: utf8Bidi 
File: D:\xampp\htdocs\coding\ujian-online-ci-master\application\libraries\Pdf.php
Line: 9
Function: __construct 
File: D:\xampp\htdocs\coding\ujian-online-ci-master\application\controllers\Hasilujian.php
Line: 73
Function: library 
File: D:\xampp\htdocs\coding\ujian-online-ci-master\index.php
Line: 315
Function: require_once 
A PHP Error was encountered
Severity: Warning
Message: chr() expects parameter 1 to be int, string given
Filename: include/tcpdf_fonts.php
Line Number: 1671
Backtrace:
File: D:\xampp\htdocs\coding\ujian-online-ci-master\application\libraries\tcpdf\include\tcpdf_fonts.php
Line: 1671
Function: chr 
File: D:\xampp\htdocs\coding\ujian-online-ci-master\application\libraries\tcpdf\include\tcpdf_fonts.php
Line: 1803
Function: unichr 
File: D:\xampp\htdocs\coding\ujian-online-ci-master\application\libraries\tcpdf\include\tcpdf_fonts.php
Line: 2099
Function: UTF8ArrSubString 
File: D:\xampp\htdocs\coding\ujian-online-ci-master\application\libraries\tcpdf\tcpdf.php
Line: 1963
Function: utf8Bidi 
File: D:\xampp\htdocs\coding\ujian-online-ci-master\application\views\ujian\cetak.php
Line: 21
Function: __construct 
File: D:\xampp\htdocs\coding\ujian-online-ci-master\application\controllers\Hasilujian.php
Line: 85
Function: view 
File: D:\xampp\htdocs\coding\ujian-online-ci-master\index.php
Line: 315
Function: require_once 
TCPDF ERROR: Some data has already been output, can't send PDF file

**Comment by wahyu303-rgb** [comment]
@arfandotid gan, apa ya solusinya?😂🙏

**Comment by arfandotid** [comment]
sudah saya perbaiki
