### ISSUE TITLE
eror instal di hosting

### ISSUE THREAD

**Issue by makmoery** [arfandotid/ujian-online-ci#5]
![eror database ci_online_test](https://user-images.githubusercontent.com/2778831/81235797-f8c3e980-9025-11ea-8976-ab0801be22be.jpg)
 ini kenapa ya...?

**Comment by makmoery** [comment]
Terus kalo mau diterapkan di sekolah (SMK), bagiamana agar dosen = guru dan mata kuliah = mata pelajaran, thanks

**Comment by RioChndr** [comment]
edit dulu konfigurasi database di file `application/config/database.php`. Pada baris kode dibawah ini, masukkan konfigurasi database di hostingnya, kaya nama database, username, dan password.
```
'hostname' => 'localhost',
	'username' => 'root',
	'password' => '',
	'database' => 'ci_online_test',
```
