### ISSUE TITLE
Error Hosting Sql,mode

### ISSUE THREAD

**Issue by antowrnto** [arfandotid/ujian-online-ci#6]
Kak Ini Mengapa yah pas di local hostjalan tapi pas di hosting ngga jalan 
Error Number: 1231

Variable 'sql_mode' can't be set to the value of 'REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE( @@sql_mode'

SELECT `users`.*, `users`.`id` as `id`, `users`.`id` as `user_id` FROM `users` WHERE `users`.`id` = '1' ORDER BY `users`.`id` DESC LIMIT 1

Filename: models/Ion_auth_model.php

Line Number: 1466

Mohon Bantuannya Kak Please:)

**Comment by mrhmt80** [comment]
mungkin link referensi ini bs membantu ... 
https://stackoverflow.com/questions/57375512/variable-sql-mode-cant-be-set-to-the-value-of-replace
